### ISSUE TITLE
Files added to "wwwroot" folder keep getting adding "<Content Remove="..." />" entries

### ISSUE THREAD

**Issue by datvm** [mingyaulee/Blazor.BrowserExtension#204]
With the latest template, for some reason everytime a new file is added to the `wwwroot` folder, this entry is added:

```
  <ItemGroup>
    <Content Remove="wwwroot\BrowserExtension1.lib.module.js" />
  </ItemGroup>
```

This is especially bad because in this case, `BrowserExtension1.lib.module.js` is not recognized at all (see #205, I am not sure if it's related or not). This happens to newly created projects from the template using Visual Studio.

```
   Blazor.BrowserExtension.Template
      Version: 2.0.2
      Details:
         Author: mingyaulee
         Owners: mingyaulee
         Reserved: ✘
         NuGetSource: https://api.nuget.org/v3/index.json
      Templates:
         Browser extension with Blazor WebAssembly (browserext) C#
      Uninstall Command:
         dotnet new uninstall Blazor.BrowserExtension.Template
```
